services:
  ros2_humble_isaaclab:
    image: legro/ros2_humble_isaaclab
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - ${OV_CACHE_PATH}:/root/.cache/ov
      - ${NV_CACHE_PATH}:/root/.nvidia/omniverse
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true

volumes:
  isaac_cache:
  isaac_nv_cache: